# fly.toml app configuration file generated for research-idea-site on 2026-01-05T18:26:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'research-idea-site'
primary_region = 'nrt'

[build]

[env]
  RACK_ENV = 'production'

[[mounts]]
  source = 'vision_shift_data'
  destination = '/app/db'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
